package:
  name: feast
  version: "0.0.1"

source:
  git_url: https://github.com/cozygene/FEAST.git
  patches: parse_options.patch

build:
  number: 6

requirements:
  build:
    - r-base >=3.5,<3.6.0a0
    - r-doparallel
    - r-foreach
    - r-dplyr
    - r-mgcv
    - r-reshape2
    - r-ggplot2
    - r-Rcpp
    - r-RcppArmadillo
    - r-philentropy
    - r-mcmcpack
    - r-lsei
    - r-vegan
    - r-cowplot
    - r-optparse
  run:
    - r-base >=3.5,<3.6.0a0
    - r-doparallel
    - r-foreach
    - r-dplyr
    - r-mgcv
    - r-reshape2
    - r-ggplot2
    - r-Rcpp
    - r-RcppArmadillo
    - r-philentropy
    - r-mcmcpack
    - r-lsei
    - r-vegan
    - r-cowplot
    - r-optparse

test:
  files:
    - test_counts.csv
    - test_meta.csv
    - test_results.csv
  commands:
    - Rscript --vanilla $CONDA_PREFIX/src/feast/feast_main.R -m test_meta.csv -c test_counts.csv -s 0 -e 1000 -r feast.results.csv
    - cat test_results.csv | cut -f 1 | sort > exp_order
    - cat feast.results.csv | cut -f 1 | sort > obs_order
    - diff exp_order obs_order

about:
  home: https://github.com/cozygene/FEAST/
  summary: 'a scalable algorithm for quantifying the origins of complex microbial communities'
  description: |
    A major challenge of analyzing the compositional structure of microbiome
    data is identifying its potential origins. Here, we introduce Fast
    Expectation-mAximization microbial Source Tracking (FEAST), a ready-to-use
    scalable framework that can simultaneously estimate the contribution of
    thousands of potential source environments in a timely manner, thereby
    helping unravel the origins of complex microbial communities. The
    information gained from FEAST may provide insight into quantifying
    contamination, tracking the formation of developing microbial communities,
    as well as distinguishing and characterizing bacteria-related health
    conditions. For more details see Shenhav et al. 2019, Nature Methods
    (https://www.nature.com/articles/s41592-019-0431-x).
