package:
  name: bugbase
  version: "0.1.0"

source:
  git_url: https://github.com/knights-lab/BugBase.git

build:
  number: 2

requirements:
  build:
    - gfortran_linux-64
    - libblas
    - liblapack
    - r-base
    - r-crayon
    - r-vctrs
    - r-withr

  run:
    - gfortran_linux-64
    - libblas
    - liblapack
    - r-base
    - r-crayon
    - r-vctrs
    - r-withr

test:
  files:
    - test_counts.txt
    - test_16s_normalized_otus.txt
    - test_contributing_otus.txt
  commands:
    - run.bugbase.r -i test_counts.txt -a -o test_results
    - diff test_contributing_otus.txt test_results/otu_contributions/contributing_otus.txt
    - diff test_16s_normalized_otus.txt test_results/normalized_otus/16s_normalized_otus.txt

about:
  home: https://github.com/knights-lab/BugBase.git
  summary: 'Analyze microbiome samples with the default phenotypes, as well as the KEGG pathways.'
  description: |
