package:
  name: picrust1
  version: "1.1.4"

#source:
#  url: https://github.com/picrust/picrust/releases/download/v1.1.4/picrust-1.1.4.tar.gz
  #sha1: 58b589b9e3d94787c1a462147e34dd8db531ba77
build:
  number: 0

requirements:
  build:
    - picrust
  run:
    - picrust

about:
  home: https://github.com/picrust/picrust
  summary: 'Phylogenetic Investigation of Communities by Reconstruction of Unobserved States'
  description: |
    The PICRUSt project aims to support prediction of the unobserved character
    states in a community of organisms from phylogenetic information about the
    organisms in that community. The primary application is to predict gene
    family abundance (e.g. the metagenome) in environmental DNA samples for
    which only marker gene (e.g. 16S rRNA gene) data are available. This is
    an open source, international, collaborative bioinformatics project
    developed in the Huttenhower, Beiko, Langille, Vega Thurber, Knight
    and Caporaso labs.
