package:
  name: sourcetracker2
  version: "2.0.1"

#source:
#  git_url: https://github.com/biota/sourcetracker2.git

build:
  number: 1

requirements:
  build:
    - python =3.5
    - numpy
    - scipy
    - scikit-bio
    - biom-format
    - h5py
    - hdf5
    - seaborn

  run:
    - python =3.5
    - numpy
    - scipy
    - scikit-bio
    - biom-format
    - h5py
    - hdf5
    - seaborn

test:
#  files:
#    - test_counts.txt
#    - test_16s_normalized_otus.txt
#    - test_contributing_otus.txt
  commands:
    - sourcetracker2 gibbs --help
#    - run.bugbase.r -i test_counts.txt -a -o test_results
#    - diff test_contributing_otus.txt test_results/otu_contributions/contributing_otus.txt
#    - diff test_16s_normalized_otus.txt test_results/normalized_otus/16s_normalized_otus.txt

about:
  home: https://github.com/biota/sourcetracker2
  summary: 'SourceTracker is designed to predict the source of microbial communities in a set of input samples (i.e., the sink samples)'
  description: |
